name: Bot Feed Updates

on: 
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"   # every minute

jobs: 
  feed-update: 
    runs-on: ubuntu-latest 

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.13.7'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirement.txt ]; then pip install -r requirement.txt; fi

      # Write Google credentials JSON in the same folder as the script
      - name: Write service account JSON
        run: |
          printf "%s" "${{ secrets.GOOGLE_CREDENTIALS }}" > Bluesky-bot/service_account.json

      # Run the bot script
      - name: Run Bot Script
        run: |
          python Bluesky-bot/CNL-Bluesky.py
          echo "Bot feed refreshed"
