name: Bot Feed Updates

on: 
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"   # every minute

jobs: 
  feed-update: 
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.13.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirement.txt ]; then pip install -r requirement.txt; fi
          pip install gspread google-auth google-auth-oauthlib google-auth-httplib2

      - name: Write service account JSON
        run: |
          printf "%s" "${{ secrets.GOOGLE_CREDENTIALS }}" > service_account.json

      - name: Debug - List files
        run: ls -R

      - name: Run Bot Script
        run: |
          python CNL-Bluesky.py
          echo "Bot feed refreshed"
